services:
  backend:
    build: ./backend
    image: backend:latest
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "127.0.0.1:8000:8000"

  auth:
    build: ./auth
    image: auth:latest
    container_name: auth
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8001:8000"

  frontend:
    build: ./frontend
    image: frontend:latest
    container_name: frontend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8002:8000"

  cart:
    build: ./cart
    image: cart:latest
    container_name: cart
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8003:8000"
